import { Document } from "@/types";

export const documents: Document[] = [
  {
    id: "doc_001",
    fileName: "Quest_Diagnostics_A1c_Panel_2026-06-10.pdf",
    type: "lab_report",
    fileType: "pdf",
    sizeKb: 412,
    uploadedDate: "2026-06-11",
    status: "processed",
    summary: "Comprehensive metabolic and A1c panel showing continued improvement in glycemic control.",
  },
  {
    id: "doc_002",
    fileName: "Emory_Radiology_Abdominal_US_2026-02-20.pdf",
    type: "imaging",
    fileType: "pdf",
    sizeKb: 1875,
    uploadedDate: "2026-02-21",
    status: "processed",
    summary: "Abdominal ultrasound report — no abnormal findings.",
  },
  {
    id: "doc_003",
    fileName: "Endocrinology_Visit_Note_2026-06-10.pdf",
    type: "clinical_note",
    fileType: "pdf",
    sizeKb: 220,
    uploadedDate: "2026-06-10",
    status: "processed",
    summary: "Visit note from Dr. Osei covering diabetes and hypertension management.",
  },
  {
    id: "doc_004",
    fileName: "Eye_Exam_Report_2024-03-05.jpg",
    type: "clinical_note",
    fileType: "jpg",
    sizeKb: 3040,
    uploadedDate: "2024-03-06",
    status: "processed",
    summary: "Diabetic eye exam — no retinopathy detected.",
  },
  {
    id: "doc_005",
    fileName: "Urgent_Care_Discharge_2023-08-14.pdf",
    type: "discharge_summary",
    fileType: "pdf",
    sizeKb: 180,
    uploadedDate: "2023-08-14",
    status: "processed",
    summary: "Discharge summary for right ankle sprain evaluation.",
  },
  {
    id: "doc_006",
    fileName: "Pharmacy_Prescription_Rosuvastatin.png",
    type: "prescription",
    fileType: "png",
    sizeKb: 640,
    uploadedDate: "2021-06-10",
    status: "processed",
  },
  {
    id: "doc_007",
    fileName: "Annual_Physical_Summary_2025-06-11.pdf",
    type: "clinical_note",
    fileType: "pdf",
    sizeKb: 305,
    uploadedDate: "2025-06-12",
    status: "processing",
  },
];
