import { Medication } from "@/types";

export const medications: Medication[] = [
  {
    id: "med_001",
    name: "Metformin",
    genericName: "Metformin HCl",
    dosage: "1000 mg",
    frequency: "Twice daily with meals",
    route: "Oral",
    prescribedBy: "Dr. Amara Osei",
    startDate: "2021-06-05",
    status: "active",
    purpose: "Type 2 Diabetes management",
    refillsRemaining: 3,
    instructions: "Take with food to reduce GI upset. Monitor for signs of lactic acidosis.",
  },
  {
    id: "med_002",
    name: "Losartan",
    genericName: "Losartan Potassium",
    dosage: "50 mg",
    frequency: "Once daily",
    route: "Oral",
    prescribedBy: "Dr. Priya Chandran",
    startDate: "2020-11-20",
    status: "active",
    purpose: "Hypertension management",
    refillsRemaining: 5,
    instructions: "Take at the same time each morning. Avoid potassium supplements.",
  },
  {
    id: "med_003",
    name: "Rosuvastatin",
    genericName: "Rosuvastatin Calcium",
    dosage: "10 mg",
    frequency: "Once daily at bedtime",
    route: "Oral",
    prescribedBy: "Dr. Amara Osei",
    startDate: "2021-06-10",
    status: "active",
    purpose: "Hyperlipidemia / LDL reduction",
    refillsRemaining: 2,
    instructions: "Report any unexplained muscle pain or weakness.",
  },
  {
    id: "med_004",
    name: "Loratadine",
    genericName: "Loratadine",
    dosage: "10 mg",
    frequency: "Once daily as needed",
    route: "Oral",
    prescribedBy: "Dr. Priya Chandran",
    startDate: "2019-04-22",
    status: "active",
    purpose: "Seasonal allergy symptom relief",
  },
  {
    id: "med_005",
    name: "Amoxicillin",
    genericName: "Amoxicillin",
    dosage: "500 mg",
    frequency: "Three times daily",
    route: "Oral",
    prescribedBy: "Dr. Kevin Marsh",
    startDate: "2022-02-14",
    endDate: "2022-02-24",
    status: "completed",
    purpose: "Bacterial sinusitis",
  },
];
