import { MedicalEvent } from "@/types";

export const timelineEvents: MedicalEvent[] = [
  {
    id: "evt_001",
    type: "office_visit",
    date: "2019-04-22",
    title: "Allergy Evaluation",
    description: "Presented with seasonal sneezing and congestion. Diagnosed with allergic rhinitis and started on loratadine.",
    provider: "Dr. Priya Chandran",
    facility: "Emory Primary Care",
    tags: ["allergy"],
  },
  {
    id: "evt_002",
    type: "procedure",
    date: "2019-06-20",
    title: "Wisdom Teeth Extraction",
    description: "Surgical extraction of all four wisdom teeth under local anesthesia. Uncomplicated recovery.",
    provider: "Dr. Lisa Yoon, DDS",
    facility: "Atlanta Oral Surgery Associates",
    tags: ["surgery"],
  },
  {
    id: "evt_003",
    type: "hospitalization",
    date: "2014-03-02",
    title: "Emergency Appendectomy",
    description: "Admitted with acute abdominal pain; diagnosed with appendicitis and underwent laparoscopic appendectomy. Discharged after 2 days.",
    provider: "Dr. Felix Nwosu",
    facility: "Piedmont Atlanta Hospital",
    tags: ["surgery", "emergency"],
  },
  {
    id: "evt_004",
    type: "office_visit",
    date: "2020-11-18",
    title: "Annual Physical — Elevated Blood Pressure",
    description: "Routine physical revealed blood pressure of 148/92. Discussed lifestyle changes and follow-up monitoring.",
    provider: "Dr. Priya Chandran",
    facility: "Emory Primary Care",
    tags: ["hypertension"],
  },
  {
    id: "evt_005",
    type: "lab_result",
    date: "2020-11-20",
    title: "Basic Metabolic Panel",
    description: "Follow-up labs ordered after elevated BP reading. Results within normal limits aside from mildly elevated glucose.",
    provider: "Dr. Priya Chandran",
    facility: "Quest Diagnostics",
    tags: ["labs"],
  },
  {
    id: "evt_006",
    type: "medication_started",
    date: "2020-11-20",
    title: "Started Losartan 50mg",
    description: "Initiated ARB therapy for essential hypertension. Advised on home BP monitoring.",
    provider: "Dr. Priya Chandran",
    tags: ["medication", "hypertension"],
  },
  {
    id: "evt_007",
    type: "lab_result",
    date: "2021-06-01",
    title: "Comprehensive Metabolic + A1c Panel",
    description: "A1c returned at 8.9%, consistent with new-onset Type 2 Diabetes. LDL also elevated at 168 mg/dL.",
    provider: "Dr. Amara Osei",
    facility: "Quest Diagnostics",
    tags: ["labs", "diabetes"],
  },
  {
    id: "evt_008",
    type: "office_visit",
    date: "2021-06-03",
    title: "New Diagnosis: Type 2 Diabetes & Hyperlipidemia",
    description: "Reviewed lab results with endocrinology. Diagnosed with Type 2 Diabetes and Hyperlipidemia. Discussed treatment plan including medication and diet.",
    provider: "Dr. Amara Osei",
    facility: "Emory Endocrinology",
    tags: ["diabetes", "diagnosis"],
  },
  {
    id: "evt_009",
    type: "medication_started",
    date: "2021-06-05",
    title: "Started Metformin 1000mg",
    description: "Initiated first-line therapy for Type 2 Diabetes, titrated to 1000mg twice daily over 2 weeks.",
    provider: "Dr. Amara Osei",
    tags: ["medication", "diabetes"],
  },
  {
    id: "evt_010",
    type: "medication_started",
    date: "2021-06-10",
    title: "Started Rosuvastatin 10mg",
    description: "Initiated statin therapy for elevated LDL cholesterol.",
    provider: "Dr. Amara Osei",
    tags: ["medication", "cholesterol"],
  },
  {
    id: "evt_011",
    type: "office_visit",
    date: "2022-02-14",
    title: "Sinusitis Evaluation",
    description: "Presented with facial pressure, congestion, and low-grade fever for 8 days. Diagnosed with acute bacterial sinusitis.",
    provider: "Dr. Kevin Marsh",
    facility: "Piedmont Urgent Care",
    tags: ["infection"],
  },
  {
    id: "evt_012",
    type: "medication_started",
    date: "2022-02-14",
    title: "Started Amoxicillin 500mg",
    description: "10-day course prescribed for bacterial sinusitis.",
    provider: "Dr. Kevin Marsh",
    tags: ["medication"],
  },
  {
    id: "evt_013",
    type: "lab_result",
    date: "2022-06-01",
    title: "Diabetes Follow-Up Panel",
    description: "A1c improved to 7.2% on current regimen. LDL down to 128 mg/dL. Continue current treatment plan.",
    provider: "Dr. Amara Osei",
    facility: "Quest Diagnostics",
    tags: ["labs", "diabetes"],
  },
  {
    id: "evt_014",
    type: "imaging_study",
    date: "2022-09-15",
    title: "Chest X-Ray",
    description: "Ordered for persistent cough. No acute cardiopulmonary abnormality identified.",
    provider: "Dr. Priya Chandran",
    facility: "Emory Radiology",
    tags: ["imaging"],
  },
  {
    id: "evt_015",
    type: "office_visit",
    date: "2023-01-15",
    title: "Diabetes & Hypertension Check-In",
    description: "Routine follow-up. Blood pressure well-controlled at 124/80. A1c trending down to 6.9%.",
    provider: "Dr. Amara Osei",
    facility: "Emory Endocrinology",
    tags: ["diabetes", "hypertension"],
  },
  {
    id: "evt_016",
    type: "hospitalization",
    date: "2023-08-14",
    title: "Urgent Care Visit — Ankle Injury",
    description: "Twisted right ankle playing recreational basketball. X-ray negative for fracture; diagnosed with Grade I sprain.",
    provider: "Dr. Kevin Marsh",
    facility: "Piedmont Urgent Care",
    tags: ["injury"],
  },
  {
    id: "evt_017",
    type: "lab_result",
    date: "2023-09-10",
    title: "Annual Labs",
    description: "A1c 6.7%, LDL 108 mg/dL. Continued improvement across metabolic markers.",
    provider: "Dr. Amara Osei",
    facility: "Quest Diagnostics",
    tags: ["labs"],
  },
  {
    id: "evt_018",
    type: "procedure",
    date: "2024-03-05",
    title: "Diabetic Eye Exam",
    description: "Routine annual dilated eye exam for diabetes screening. No signs of diabetic retinopathy.",
    provider: "Dr. Sandra Kim, Ophthalmology",
    facility: "Emory Eye Center",
    tags: ["diabetes", "screening"],
  },
  {
    id: "evt_019",
    type: "lab_result",
    date: "2024-06-12",
    title: "Diabetes & Lipid Follow-Up",
    description: "A1c 6.6%, LDL 104 mg/dL. Kidney function stable. Continue current medications.",
    provider: "Dr. Amara Osei",
    facility: "Quest Diagnostics",
    tags: ["labs"],
  },
  {
    id: "evt_020",
    type: "office_visit",
    date: "2025-06-11",
    title: "Annual Physical",
    description: "Overall stable health. Reviewed medication adherence and lifestyle habits. All chronic conditions well-controlled.",
    provider: "Dr. Priya Chandran",
    facility: "Emory Primary Care",
    tags: ["annual"],
  },
  {
    id: "evt_021",
    type: "lab_result",
    date: "2025-06-11",
    title: "Comprehensive Metabolic + Lipid Panel",
    description: "A1c 6.5%, LDL 101 mg/dL, eGFR 93. Trending consistently in the right direction.",
    provider: "Dr. Amara Osei",
    facility: "Quest Diagnostics",
    tags: ["labs"],
  },
  {
    id: "evt_022",
    type: "imaging_study",
    date: "2026-02-20",
    title: "Abdominal Ultrasound",
    description: "Ordered as routine screening given metabolic history. No abnormal findings; liver and kidneys unremarkable.",
    provider: "Dr. Amara Osei",
    facility: "Emory Radiology",
    tags: ["imaging"],
  },
  {
    id: "evt_023",
    type: "office_visit",
    date: "2026-06-10",
    title: "Diabetes & Hypertension Check-In",
    description: "A1c down to 6.4%, closest to target range yet. Blood pressure 126/82. Discussed continuing current regimen with quarterly monitoring.",
    provider: "Dr. Amara Osei",
    facility: "Emory Endocrinology",
    tags: ["diabetes", "hypertension"],
  },
];
